In [1]:
from test_MDbrew.opener import DumpOpener
from test_MDbrew.tools import Extractor
from test_MDbrew.MSD import MSD

path = './test.lammpstrj'
data = DumpOpener(path)
database = Extractor(data=data).get_position_db(type_=1)

 STEP (Done) :  get_database	 	->  1.45 s ✅ 
 STEP (Done) :  get_columns	 	->  0.00 s ✅ 
 STEP (Done) :  get_position_db	 	->  0.67 s ✅ 


In [2]:
msd = MSD(database)
msd.get_msd(method="direct", fft=True)
msd.get_msd(method="window", fft=False)
msd.get_msd(method="window", fft=True)


 MSD  (STEP) : 100%|############| 401/401 [00:00<00:00, 160964.29it/s]


array([-9.15179044e-15,  2.27837890e+02,  2.76597264e+02,  2.96088168e+02,
        3.04621781e+02,  3.08114724e+02,  3.09258621e+02,  3.10213267e+02,
        3.10457044e+02,  3.10439576e+02,  3.10046749e+02,  3.10459324e+02,
        3.10388334e+02,  3.11157133e+02,  3.10881853e+02,  3.10697260e+02,
        3.10165836e+02,  3.10413465e+02,  3.10294834e+02,  3.09711203e+02,
        3.09825979e+02,  3.10502788e+02,  3.10804724e+02,  3.10821727e+02,
        3.10530759e+02,  3.10488346e+02,  3.09961999e+02,  3.09984780e+02,
        3.10163221e+02,  3.10485371e+02,  3.10254162e+02,  3.10157080e+02,
        3.09931560e+02,  3.09919248e+02,  3.09778633e+02,  3.10290740e+02,
        3.10420920e+02,  3.09878169e+02,  3.10079905e+02,  3.10243463e+02,
        3.10158171e+02,  3.10119010e+02,  3.10480982e+02,  3.09799225e+02,
        3.10361937e+02,  3.10046925e+02,  3.09825796e+02,  3.10384779e+02,
        3.10303481e+02,  3.10010362e+02,  3.10192700e+02,  3.10305225e+02,
        3.10697446e+02,  

In [3]:
import numpy as np
axis_dict = {"lag": 0, "N_particle": 1, "pos": -1}
position = np.array(database)
N, N_particle = position.shape[:2]

empty_matrix = np.zeros((N, N_particle))
D = np.square(position).sum(axis=axis_dict["pos"])
D = np.append(D, empty_matrix, axis=axis_dict["lag"])
Q = 2 * np.sum(D, axis=axis_dict["lag"])
S_1 = empty_matrix
for m in range(N):
    Q -= D[m - 1, :] + D[N - m, :]
    S_1[m, :] = Q / (N - m)
# S_2 = self.__auto_correlation()
# msd_list = np.subtract(S_1, 2 * S_2)
# self.__mean_msd_list(msd_list=msd_list)

In [4]:
S_1

array([[300.91918746, 288.904763  , 332.87885263, ..., 294.99952665,
        298.13111057, 310.86441551],
       [300.94831044, 288.71134148, 332.8760574 , ..., 294.91997105,
        298.1522047 , 310.7547894 ],
       [300.79741045, 289.11004019, 332.80892803, ..., 294.71578722,
        298.16882806, 310.80702141],
       ...,
       [319.0340085 , 237.1055929 , 390.23926444, ..., 347.33188311,
        332.23711568, 314.20996445],
       [325.21369956, 247.95196377, 346.82880989, ..., 351.60554299,
        290.60647076, 322.31453774],
       [289.26999448, 366.27337381, 333.9969422 , ..., 326.82176676,
        289.6934563 , 354.71485623]])

In [5]:
D.shape

(802, 1000)

In [6]:
Q

array([289.26999448, 366.27337381, 333.9969422 ,  79.7455409 ,
       290.8352587 , 264.45431562, 219.30329476, 258.0222813 ,
       373.26400453, 101.67971845, 288.09998137, 198.61090316,
       174.75737544, 300.18557894, 214.02125233, 224.02572584,
       310.78616889, 359.89890198, 227.27746543, 322.53399773,
       283.10177527, 422.19655842, 257.30192425, 278.54893799,
       190.68487162, 263.13482673, 461.75097681, 401.47705959,
       283.96154494, 333.59119131, 382.31593545, 243.70897971,
       335.90594211, 248.63369744, 275.4035291 , 220.35131316,
       291.18333124, 196.3020603 , 237.03471495, 423.35183377,
        93.74471811, 409.35622473, 299.27489682, 166.18059589,
       263.27340494, 277.43516027, 428.74277953, 281.29005771,
       188.05299999, 446.14478409, 214.41937754, 277.31824974,
       294.89723104, 265.83571737, 280.35276507, 193.52940602,
       285.35734207, 528.44111133, 432.33440851, 159.50073831,
       356.87659694, 436.53902669, 424.8869122 , 273.93