In [7]:
from MDbrew.opener import DumpOpener
from MDbrew.tools import Extractor, timeCount
data = DumpOpener('./test.lammpstrj')
pos = Extractor(data=data).get_position_db(type_=1)


	 1 data is generated 

	get_position_db :  0.94 s


In [4]:
test_pos = pos[0]
test_pos

array([[ -2.48633 ,  -2.35502 , -10.7829  ],
       [  3.83049 ,   4.1636  ,   6.99809 ],
       [ -1.75142 ,  -6.93071 ,  -7.37398 ],
       ...,
       [ -5.38083 ,  -4.67541 ,  -4.99413 ],
       [ -0.685927,   6.02371 ,   9.95924 ],
       [ -5.16088 ,   1.02911 ,  -9.38684 ]])

In [30]:
import time
import numpy as np
s = time.time()
r_ = []
ss = [10, 10, 10]
for i in test_pos:
    for j in test_pos:
        r = np.abs(i-j)
        for idx, ps in enumerate(r):
            if ps > ss[idx]:
                r[idx] = ss[idx] - ps
        r_.append(r)
e = time.time()
print(e-s)
r_

2.7084295749664307


[array([0., 0., 0.]),
 array([ 6.31682,  6.51862, -7.78099]),
 array([0.73491, 4.57569, 3.40892]),
 array([6.36969, 7.42709, 0.2853 ]),
 array([ 1.00367,  9.43585, -8.0979 ]),
 array([ 5.40767, -1.90047, -5.6308 ]),
 array([4.90563, 0.26476, 2.50697]),
 array([0.84125, 2.6642 , 5.93198]),
 array([  2.10093,   2.2771 , -11.7017 ]),
 array([3.35446 , 1.965057, 3.8887  ]),
 array([ 5.63635,  8.04793, -8.60597]),
 array([  5.64874,   6.98309, -10.57344]),
 array([ 6.42017, -0.65735,  0.91271]),
 array([ 3.432099, -1.9605  ,  0.0462  ]),
 array([ 4.65512, -0.77546, -4.95473]),
 array([ 5.5834 ,  9.09569, -6.71425]),
 array([1.55928, 1.82268, 7.62773]),
 array([ 3.10051,  2.44775, -9.89107]),
 array([5.0606 , 8.46356, 1.56463]),
 array([0.19499, 2.55869, 2.69882]),
 array([ 2.846526,  9.57041 , -5.51379 ]),
 array([2.19674 , 1.878398, 4.34213 ]),
 array([7.39168, 1.65246, 2.5928 ]),
 array([  3.75334,   6.93491, -11.3673 ]),
 array([0.14317, 2.4553 , 1.27108]),
 array([  1.716505,  -2.2458  